### PR TITLE
Fixed issue #2

### LINKED ISSUE #2: Add error logs in helpers.generators.go
Add proper **error logs** describing the issue in generate functions

### PR DESCRIPTION
**Pull request by sarveshdakhore**
Fixed #2 

this includes fixed of issue #1 too because they are dependent

### CODE REVIEW

File: internal/helpers/generators.go [hunk 1]
```diff
@@ -14,32 +15,34 @@ func GenerateDatabaseFile(folderPath string, provider Provider) error {
...
 
 func ConnectDB(){
-	{{.ConnectionCode}}
+    {{.ConnectionCode}}
 }
 `)
 	if err != nil {
-		return 
+		log.Printf("error parsing database template: %v", err)
+		return fmt.Errorf("error parsing database template: %v", err)
```
Comment (TejasGhatte) [inline internal/helpers/generators.go:32]: no need of both log.printf and fmt.errorf as it will log the error two times, keep one

Comment (sarveshdakhore) [reply internal/helpers/generators.go:32]: Okk

**Comment by sarveshdakhore** [comment]
Updated

**Review by TejasGhatte — APPROVED** [review]
